name: cdc

on:
  watch:
  schedule:
    - cron: '10 05 * * *'
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: install env 
      run: |
        sudo apt-get update 
        sudo apt-get -y install r-base python3 python3-pip

      
    - name: run
      run: |
        pip3 install pandas
        cd CDC_data;python3 update.py
        
    - name: commit
      run: |
        git config --global user.email "783557789@qq.com"
        git config --global user.name "Robot"
        git pull
        git add .; git commit -m 'cdc-update'

    - name: GitHub Push
      uses: ad-m/github-push-action@v0.5.0
      with:
        # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # Repository name to push. Default or empty value represents current github repository (${GITHUB_REPOSITORY})
